loader_path: "../loaders/HAPTNET_loader/config/haptnet.yaml"

train_dataset: ""
val_dataset: ""
test_dataset: ""

batch: 16
num_epochs: 500
num_folds: 5
learning_rate: 1e-3


# remember to put '/' at he end of the path
log_dir: "iros2022/"

# None, SingleHop, DoubleHop - residual connection type

model_configs:
  -
    name: "Late_imu0"
    modalities: ["imu0","imu1"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_imu1"
    modalities: ["imu1"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_imu2"
    modalities: ["imu2"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_imu3"
    modalities: ["imu3"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_all_1"
    modalities: ["force","imu0","imu1","imu2","imu3"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_all_1"
    modalities: ["force","imu0","imu1","imu2","imu3"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["DoubleHop","DoubleHop","DoubleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_all_3"
    modalities: ["force","imu0","imu1","imu2","imu3"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","DoubleHop","DoubleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]
  -
    name: "Late_force"
    modalities: ["force"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 64,64,64 ]
    conv_kernels: [ 3,3,3 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: False
    fc_units: [100,6]





