loader_path: "../loaders/HAPTNET_loader/config/haptnet.yaml"

train_dataset: ""
val_dataset: ""
test_dataset: ""

batch: 16
num_epochs: 250
num_folds: 5
learning_rate: 1e-3


# remember to put '/' at he end of the path
log_dir: "iros2022/"

model_configs:
  -
    name: "forces_RNN"
    modalities: ["force","imu0"]
    fusion_type: None
    dropout: 0.1
    return_sequences: False
  -
    name: "imu_shank_RNN"
    modalities: ["imu0"]
    fusion_type: None
    dropout: 0.1
    return_sequences: False
  -
    name: "imu_toes_RNN"
    modalities: ["imu1"]
    fusion_type: None
    dropout: 0.1
    return_sequences: False
  -
    name: "imu_bridge_RNN"
    modalities: ["imu2"]
    fusion_type: None
    dropout: 0.1
    return_sequences: False
  -
    name: "imu_heel_RNN"
    modalities: ["imu3"]
    fusion_type: None
    dropout: 0.1
    return_sequences: False
