loader_path: "../loaders/HAPTNET_loader/config/haptnet.yaml"

train_dataset: ""
val_dataset: ""
test_dataset: ""

batch: 16
num_epochs: 250
num_folds: 5
learning_rate: 1e-3


# remember to put '/' at he end of the path
log_dir: "iros2022/"

# None, SingleHop, DoubleHop - residual connection type

model_configs:
  -
    name: "Late_1"
    modalities: ["force","imu0"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["None", "SingleHop","SingleHop","SingleHop"]
    conv_filters: [ 16,32,32,64 ]
    conv_kernels: [ 5,5,5,5 ]
    conv_strides: [ 2,2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: True
    fc_units: [100,6]
  -
    name: "Late_2"
    modalities: ["force","imu0"]
    fusion_type: "late"
    dropout: 0.5
    conv_types: ["None", "SingleHop","SingleHop"]
    conv_filters: [ 16,32,64 ]
    conv_kernels: [ 5,5,5 ]
    conv_strides: [ 2,2,2 ]
    lstm_nest: 3
    lstm_units: 128
    return_sequences: True
    stateful: True
    fc_units: [100,6]



