path_to_dataset: "../../datasets/QCAT/"
save_to_pickle: False
# Modalities:
# 0,1,2 - front left XYZ,
# 3,4,5 - front right XYZ,
# 6,7,8 - back right XYZ,
# 9,10,11 - back left XYZ.
modalities: [0,1,2,3,4,5,6,7,8,9,10,11]

