#path_to_dataset: "../../datasets/HAPTNET/ip_dataset_final_4.pkl"
path_to_dataset: "../datasets/HAPTNET/haptnet_2_preprocessed.pkl"
save_to_pickle: False
# Structure
# class: [0,0,0,0,1,0]
# numpy array - force XYZ,
# numpy array - imu0 XYZW, imu1 XYZW, imu2 XYZW, imu3 XYZW,
# ...
modalities:
  force: True
  imu0: True
  imu1: True
  imu2: True
  imu3: True
